services
  - type web
    name tomrico-n8n
    env docker
    repo httpsgithub.comn8n-ion8n
    plan free
    dockerfilePath Dockerfile
    envVars
      - key N8N_HOST
        value tomrico-n8n.onrender.com
      - key N8N_PORT
        value 10000
      - key PORT
        value 10000
      - key N8N_PROTOCOL
        value https
      - key WEBHOOK_URL
        value httpstomrico-n8n.onrender.com
      - key N8N_EDITOR_BASE_URL
        value httpstomrico-n8n.onrender.com
      # אופציונלי אם תרצה הפעלת הרשאות בסיס
      # - key N8N_BASIC_AUTH_ACTIVE
      #   value true
      # - key N8N_BASIC_AUTH_USER
      #   value yourusername
      # - key N8N_BASIC_AUTH_PASSWORD
      #   value yourpassword