services:
  - type: web
    name: tomrico-n8n
    env: docker
    image: docker.n8n.io/n8nio/n8n:latest
    plan: free
    startCommand: n8n start
    envVars:
      - key: N8N_HOST
        value: tomrico-n8n.onrender.com
      - key: N8N_PORT
        value: 10000
      - key: PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://tomrico-n8n.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://tomrico-n8n.onrender.com
